### PR TITLE
allow a-z and A-Z as bank identifier can be alphanumeric

### PR DESCRIPTION
**Pull request by Remo**
characters from 50 to 59 are used for bank internal references and can contain letters according to the VESR specification by ZKV

### CODE REVIEW

**Comment by sprain** [comment]
Thanks for contributing.

The tests fail now. Would you mind having a look and also add test cases for your changes?

**Comment by Remo** [comment]
Thanks for adding travis! I've updated the tests. I've replaced the letter `A` with a `.` to produce an exception. However, I'm not 100% sure if that's correct. All I can tell is that I got a file with `YZ` in it which according to their spec is possible. They don't say anything about fancier characters..

**Comment by sprain** [comment]
Thx. I will have a look this week.

**Comment by Remo** [comment]
Sorry for being pushy, but can you please let me know if you're too busy? I'll temporarily register my own fork on packagist if you are, but I'd prefer not to do that. Thanks

**Comment by sprain** [comment]
Sorry for the delay. Thanks for contributing!

**Comment by Remo** [comment]
Awesome! Thanks for sharing this library on github!

**Pull request merged**
